### ISSUE TITLE
Cant open game files menu

### ISSUE THREAD

**Issue by mcdankey** [terabyte25/tes3mp-android#14]
When i try to open "game files" menu on my Samsung galaxy A51 game just crashes. Plz help! 😭

**Comment by fenixfx** [comment]
Same problem here
Device: Pixel 4
OS: Android 11
App version: 1/21
Stacktrace:
07-09 14:15:17.018 32397 32397 E AndroidRuntime: FATAL EXCEPTION: main
07-09 14:15:17.018 32397 32397 E AndroidRuntime: Process: is.terrabyte.omw.debug, PID: 32397
07-09 14:15:17.018 32397 32397 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.populateList(ChooserDialogFragment.java:262)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.initListView(ChooserDialogFragment.java:115)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.getLayout(ChooserDialogFragment.java:85)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.onCreateDialog(ChooserDialogFragment.java:300)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at android.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:417)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at android.app.Fragment.performGetLayoutInflater(Fragment.java:1322)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7664)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-09 14:15:17.018 32397 32397 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by CLosetGoblin** [comment]
I have the same problem as well I suspect it has something to do with android 11 because that's the main similarity I can see. Im going to "attempt" to make my own apk file for this and if I do end up succeeding and it allows me to select my game files Ill share my results here!

**Comment by Doc522** [comment]
Hey, I have the same issue. I however don't know how to code or anything so I guess I'll just sit and wait and hope...

**Comment by phoenixbyrd** [comment]
Same issue here on a fold 3 with android 12, was really looking forward to this!!!

**Comment by 1YarKan1** [comment]
Не решилась проблема? Я просто недавно приобрёл xiaomi redmi note 11 и вот не получается указать путь к файлам игры (

**Comment by HappyDoggo-san** [comment]
So isn't there a way to manually set the game files location? It's driving me nuts

**Comment by InconsolableCellist** [comment]
It looks like the released APK is out of date, but even compiling a new version it doesn't appear to have access to /storage/emulated/0/Android/data/com.libopenmw.openmw, so it can't create the dir or find any config files

I increased the supported SDK version but the Config helper class still doesn't have access to that directory. I started refactoring it to use scoped storage, but there are a lot of calls into Config and making it non-static was a pain.

There are upstream changes that fix this on modern phones, as OpenMW-Nightly works on my Z Fold 4 with Android 13

**Comment by HappyDoggo-san** [comment]
> It looks like the released APK is out of date, but even compiling a new version it doesn't appear to have access to /storage/emulated/0/Android/data/com.libopenmw.openmw, so it can't create the dir or find any config files
> 
> I increased the supported SDK version but the Config helper class still doesn't have access to that directory. I started refactoring it to use scoped storage, but there are a lot of calls into Config and making it non-static was a pain.
> 
> There are upstream changes that fix this on modern phones, as OpenMW-Nightly works on my Z Fold 4 with Android 13

Exactly, the openmw one works fine. 
Isn't there a way to apply the same fix?
